hystrix:
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 10000
          timeout:
            enabled: false
feign:
  hystrix:
    enabled: false
spring:
  redis:
    timeout: 6000
    cluster:
      nodes:
      - 192.168.2.217:7000
      - 192.168.2.217:7001
      - 192.168.2.218:7000
      - 192.168.2.218:7001
      - 192.168.2.219:7000
      - 192.168.2.219:7001
    pool:
      max-active: 300
      max-wait: -1
      max-idle: 100
      min-idle: 20
    database: 0
debug: false
logging:
  level:
    root: info
    com.qq.weixin.api.cgibin.CgibinClient: debug
    com.qq.weixin.api.datacube.DataCubeClient: debug
    com.qq.weixin.api.sns.SnsClient: debug
    com.qq.weixin.api.wxa.WxaClient: debug