hystrix:
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 10000
          timeout:
            enabled: false
feign:
  hystrix:
    enabled: false
