hystrix:
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 10000
          timeout:
            enabled: false
feign:
  hystrix:
    enabled: false
spring:
  redis:
    timeout: 6000
    cluster:
      nodes:
       - 192.168.2.39:7000
       - 192.168.2.39:7001
       - 192.168.2.39:7002
       - 192.168.2.39:7003
       - 192.168.2.39:7004
       - 192.168.2.39:7005
    pool:
      max-active: 300
      max-wait: -1
      max-idle: 100
      min-idle: 20
    database: 0
debug: false
logging:
  level:
    root: info
    com.qq.weixin.api.cgibin.CgibinClient: debug
    com.qq.weixin.api.datacube.DataCubeClient: debug
    com.qq.weixin.api.sns.SnsClient: debug
    com.qq.weixin.api.wxa.WxaClient: debug
wechat:
  open:
    componentAppId: "wxb5520b267480440f"
    componentSecret: "f40c04b3bf49c74fc9b836b546948160"
    componentToken: "test123"
    componentAesKey: "1234567890a1234567890b1234567890c1234567890"
    jumpUrl: "/wxopen/auth/jump"
